[workspace]
resolver = "2"
members = ["cli", "core", "runtime"]

[workspace.package]
authors = ["the Andromeda team"]
edition = "2021"
license = "Mozilla Public License 2.0"
repository = "https://github.com/tryandromeda/andromeda"
version = "0.1.0"


[workspace.dependencies]
clap = { version = "4.5.16", features = ["derive"] }
cliclack = "0.3.3"
console = "0.15.8"
miette = { version = "7.2.0", features = ["fancy"] }
nova_vm = { git = "https://github.com/trynova/nova", branch = "main", features = ["typescript"] }
oxc_ast = "0.24.3"
oxc_parser = "0.24.3"
oxc_span = "0.24.3"
oxc_diagnostics = "0.24.3"
oxc_semantic = "0.24.3"
andromeda-core = { path = "core" }
andromeda-runtime = { path = "runtime" }
anymap = "0.12.1"
tokio = { version = "1.39.0", features = ["rt", "sync", "time"]}
