[package]
name = "andromeda-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../README.md"

[features]
default = []
canvas = ["dep:wgpu", "dep:image"]

[dependencies]
andromeda-core.workspace = true
anyhow.workspace = true
nova_vm.workspace = true
anymap.workspace = true
tokio.workspace = true
oxc-miette.workspace = true
oxc_diagnostics.workspace = true
serde.workspace = true
url.workspace = true
base64-simd.workspace = true
wgpu = { workspace = true, optional = true }
image = { workspace = true, optional = true }
