name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Set up Rust toolchain version
        run: echo "TOOLCHAIN_VERSION=$(cat rust-toolchain | tr -d '\n' | tr -d ' ')" >> $GITHUB_ENV
      - name: Install Rust toolchain
        run: |
          rustup set profile minimal
          rustup install "$TOOLCHAIN_VERSION"
          rustup default "$TOOLCHAIN_VERSION"
          rustup component add rustfmt clippy llvm-tools-preview rustc-dev
          rustup show    
      - name: Test
        run: cargo test
        timeout-minutes: 20
      - name: Spell check
        uses: crate-ci/typos@master
      - name: Check formatting
        run: cargo fmt --check
      - name: Clippy
        run: |
          cargo clippy --all-targets -- -D warnings
          cargo +$TOOLCHAIN_VERSION clippy --all-targets --all-features -- -D warnings